# Generated by Django 4.1.2 on 2022-10-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Servicio',
        ),
    ]
